### PR TITLE
[master] Added check to know whether a file is actually a gzip file or not

### PR DESCRIPTION
**Pull request by LcTrKiD**

### CODE REVIEW

**Comment by grahampugh** [comment]
Hi @LcTrKiD , can you tell me what this fixes? I merged in some changes from Greg's `installinstallmacos.py` already, but maybe I missed something since then. Could you give me an example of a failed output when this is not there. I ask because I do not like to deviate too much from Greg's version in case I lose the ability to merge upstream changes in the future.

**Comment by LcTrKiD** [comment]
Sorry @grahampugh,  I forgot to add a description. 

In my case the catalog, for a reason I can't understand was being downloaded with .gz extension but it wasn't actually a gzip file.

` joaquin  ~/github/macadmin-scripts-grahampugh/macadmin-scripts   master  gl
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 13 (delta 9), reused 10 (delta 7), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/grahampugh/macadmin-scripts
   42b1840..e45b738  master     -> origin/master
Updating 42b1840..e45b738
Fast-forward
 installinstallmacos.py | 17 +++++++++--------
 1 file changed, 9 insertions(+), 8 deletions(-)
 joaquin  ~/github/macadmin-scripts-grahampugh/macadmin-scripts   master  sudo ./installinstallmacos.py --seedprogram DeveloperSeed
Password:

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro14,1

Bridge ID        : None
Board ID         : Mac-B4831CEBD52A0C4C
OS Version       : 10.15.6
Build ID         : 19G73

Traceback (most recent call last):
  File "./installinstallmacos.py", line 1205, in <module>
    main()
  File "./installinstallmacos.py", line 843, in main
    su_catalog_url, args.workdir, ignore_cache=args.ignore_cache
  File "./installinstallmacos.py", line 537, in download_and_parse_sucatalog
    content = the_file.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 260, in read
    self._read(readsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 302, in _read
    self._read_gzip_header()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 196, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
`

**Comment by LcTrKiD** [comment]
Btw, I got the same error with Greg's version

**Comment by grahampugh** [comment]
Thanks, I saw somebody mention an issue with alternative catalogs. I'll take a look.

**Comment by grahampugh** [comment]
Hi @LcTrKiD Greg fixed this in the upstream `installinstallmacos.py` in a different way (https://github.com/munki/macadmin-scripts/issues/68), so I don't need this, but thanks for the efforts!

**Comment by LcTrKiD** [comment]
munki#68 seems like a better solution.
Thanks you!

**Pull request merged**
